import * as fs from 'fs';
import * as path from 'path';
import { loadSnapshot, listSnapshots } from './snapshot';

/**
 * Supported export formats for environment snapshots.
 */
export type ExportFormat = 'dotenv' | 'json' | 'shell';

/**
 * Options for exporting a snapshot.
 */
export interface ExportOptions {
  format: ExportFormat;
  outputPath?: string; // If omitted, returns the string instead of writing to disk
}

/**
 * Converts a snapshot's key-value pairs to .env format.
 * Keys with special characters in values are quoted.
 */
export function formatDotenv(env: Record<string, string>): string {
  return Object.entries(env)
    .map(([key, value]) => {
      // Quote values that contain spaces, newlines, or special shell characters
      const needsQuoting = /[\s"'\\$`!#&;|<>(){}]/.test(value);
      const formatted = needsQuoting ? `"${value.replace(/"/g, '\\"')}"` : value;
      return `${key}=${formatted}`;
    })
    .join('\n');
}

/**
 * Converts a snapshot's key-value pairs to shell export statements.
 * Suitable for sourcing in bash/zsh.
 */
export function formatShell(env: Record<string, string>): string {
  const lines = ['#!/bin/sh', '# Generated by snapenv', ''];
  for (const [key, value] of Object.entries(env)) {
    const escaped = value.replace(/'/g, "'\\''")
    lines.push(`export ${key}='${escaped}'`);
  }
  return lines.join('\n');
}

/**
 * Exports a snapshot to the specified format.
 * Returns the formatted string, and optionally writes it to a file.
 *
 * @param snapshotName - The name of the snapshot to export
 * @param options - Export format and optional output path
 * @param snapshotsDir - Directory where snapshots are stored
 * @returns The formatted export string
 * @throws If the snapshot does not exist
 */
export function exportSnapshot(
  snapshotName: string,
  options: ExportOptions,
  snapshotsDir: string
): string {
  const env = loadSnapshot(snapshotName, snapshotsDir);

  let output: string;

  switch (options.format) {
    case 'dotenv':
      output = formatDotenv(env);
      break;
    case 'shell':
      output = formatShell(env);
      break;
    case 'json':
      output = JSON.stringify(env, null, 2);
      break;
    default:
      throw new Error(`Unsupported export format: ${options.format}`);
  }

  if (options.outputPath) {
    const dir = path.dirname(options.outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(options.outputPath, output, 'utf-8');
  }

  return output;
}

/**
 * Exports all snapshots in a directory as a single JSON object,
 * keyed by snapshot name. Useful for backup or migration.
 *
 * @param snapshotsDir - Directory where snapshots are stored
 * @returns JSON string of all snapshots
 */
export function exportAllSnapshots(snapshotsDir: string): string {
  const names = listSnapshots(snapshotsDir);
  const all: Record<string, Record<string, string>> = {};

  for (const name of names) {
    all[name] = loadSnapshot(name, snapshotsDir);
  }

  return JSON.stringify(all, null, 2);
}
